window.TIMELESS_PAGE_DATA = {
  seasons: {
    pageTitle: 'SEASONS OF KNUT',
    headingHtml: '<b>자연이 물든 캠퍼스의 계절 풍경</b>을 담다.',
    items: [
      { title: '노란 빛이 스며든 대학본부', date: '', image: '../img/high_01_01.jpg' },
      { title: '꽃이 흐르는 충주캠퍼스 건설환경관', date: '', image: '../img/high_01_01.jpg' },
      { title: '핑크빛으로 물든 봄날의 길', date: '', image: '../img/high_01_01.jpg' },
      { title: '캠퍼스에 내려앉은 봄의 표정', date: '', image: '../img/high_01_01.jpg' },
      { title: '초록 길 위의 충주캠퍼스 중원생활관', date: '', image: '../img/high_01_01.jpg' },
      { title: '여름 대학본부에서 바라본 충주캠퍼스의 전경', date: '', image: '../img/high_01_01.jpg' },
      { title: '여름의 빛을 머금은 충주캠퍼스 대학로', date: '', image: '../img/high_01_01.jpg' },
      { title: '초록이 더해진 충주캠퍼스 공동실험실습관', date: '', image: '../img/high_01_01.jpg' },
      { title: '푸른 하늘과 증평캠퍼스 보건관', date: '', image: '../img/high_01_01.jpg' },
      { title: '한낮의 분수와 증평캠퍼스 청아관', date: '', image: '../img/high_01_01.jpg' },
      { title: '짙어진 녹음과 아우러진 증평캠퍼스 청아생활관', date: '', image: '../img/high_01_01.jpg' },
      { title: '여름 무지개 띈 인문사회관', date: '', image: '../img/high_01_01.jpg' },
      { title: '해질녘의 증평캠퍼스', date: '', image: '../img/high_01_01.jpg' },
      { title: '노을이 지는 하늘 아래 충주캠퍼스', date: '', image: '../img/high_01_01.jpg' },
      { title: '은행나무 길이 이어진 충주캠퍼스 대학로', date: '', image: '../img/high_01_01.jpg' },
      { title: '가을이 물든 충주캠퍼스', date: '', image: '../img/high_01_01.jpg' },
      { title: '붉게 물든 나무 사이로 마주한 증평캠퍼스 보건관', date: '', image: '../img/high_01_01.jpg' },
      { title: '가을 숲에 둘러싸인 증평캠퍼스 국제관', date: '', image: '../img/high_01_01.jpg' },
      { title: '낙엽과 시간이 쌓인 의왕캠퍼스 본관', date: '', image: '../img/high_01_01.jpg' },
      { title: '가을의 시간이 흐르는 충주캠퍼스 대학로', date: '', image: '../img/high_01_01.jpg' },
      { title: '울긋불긋 색으로 물든 증평캠퍼스 길', date: '', image: '../img/high_01_01.jpg' },
      { title: '가을빛이 머문 충주캠퍼스의 길', date: '', image: '../img/high_01_01.jpg' },
      { title: '눈이 소복히 내려앉은 충주캠퍼스 공동실험실습관', date: '', image: '../img/high_01_01.jpg' },
      { title: '겨울의 시간 속에서도 이어지는 일상', date: '', image: '../img/high_01_01.jpg' },
      { title: '눈 내린 문을 여는 충주캠퍼스 정문', date: '', image: '../img/high_01_01.jpg' },
      { title: '겨울의 고요함, 증평캠퍼스', date: '', image: '../img/high_01_01.jpg' },
      { title: '겨울을 품은 충주캠퍼스의 풍경', date: '', image: '../img/high_01_01.jpg' }
    ]
  },
  scenes: {
    pageTitle: 'SCENES OF KNUT',
    headingHtml: '<b>설렘, 행복의 순간</b>이 담긴 시간을 잇다.',
    items: [
      { title: '운수학교 전기과 입학 기념 사진', date: '1946. 09.', image: '../img/high_01_01.jpg' },
      { title: '충주공업전문대학 입학식', date: '1989.', image: '../img/high_01_01.jpg' },
      { title: '충주대학교 입학식', date: '2004.', image: '../img/high_01_01.jpg' },
      { title: '2021학년도 입학식', date: '2021. 03. 02.', image: '../img/high_01_01.jpg' },
      { title: '2022학년도 입학식', date: '2022. 03. 02.', image: '../img/high_01_01.jpg' },
      { title: '2025학년도 입학식', date: '2025.', image: '../img/high_01_01.jpg' },
      { title: '총학생회 출범식', date: '1992.', image: '../img/high_01_01.jpg' },
      { title: '총학생회 해오름식', date: '2002. 03. 20.', image: '../img/high_01_01.jpg' },
      { title: '총학생회 해오름식', date: '2016. 03. 30.', image: '../img/high_01_01.jpg' },
      { title: '총학생회 해오름식', date: '2018. 03. 22.', image: '../img/high_01_01.jpg' },
      { title: '영어동아리 ESC 창단멤버사진', date: '1989.', image: '../img/high_01_01.jpg' },
      { title: '개교110주년기념 대학문화의 거리 조성을 위한 대학로 문화행사', date: '2015.', image: '../img/high_01_01.jpg' },
      { title: '2024학년도 지역주민과 함께하는 음악동아리 문화 공연', date: '2024. 05. 30.', image: '../img/high_01_01.jpg' },
      { title: '개교 120주년 기념 지역주민과 함께하는 연극동아리 문화공연', date: '2025. 05 28.', image: '../img/high_01_01.jpg' },
      { title: '국원대동제', date: '1998. 09. 25.', image: '../img/high_01_01.jpg' },
      { title: '대동제', date: '2008.', image: '../img/high_01_01.jpg' },
      { title: '국원대동제', date: '2012. 10. 09.', image: '../img/high_01_01.jpg' },
      { title: '대동제', date: '2025.', image: '../img/high_01_01.jpg' },
      { title: '보건생명대학 체육대회', date: '2007. 05. 16.', image: '../img/high_01_01.jpg' },
      { title: '국원체육대회', date: '2009. 05. 14.', image: '../img/high_01_01.jpg' },
      { title: '증평캠퍼스 체육대회', date: '2016. 05. 04.', image: '../img/high_01_01.jpg' },
      { title: '인문사회대학 체육대회', date: '2024.', image: '../img/high_01_01.jpg' },
      { title: '에이플러스 빵 나눠주기', date: '2009.', image: '../img/high_01_01.jpg' },
      { title: '간식 이벤트(박준훈 총장)', date: '2020.', image: '../img/high_01_01.jpg' },
      { title: '커피차 이벤트', date: '2023.', image: '../img/high_01_01.jpg' },
      { title: '총장이 쏜다(윤승조 총장)', date: '2025.', image: '../img/high_01_01.jpg' },
      { title: '운수학교 전기과 1회 졸업식', date: '1947.', image: '../img/high_01_01.jpg' },
      { title: '졸업식 기념 사진', date: '1965.', image: '../img/high_01_01.jpg' },
      { title: '2018학년도. 후기 학위수여식', date: '2019. 08. 22.', image: '../img/high_01_01.jpg' },
      { title: '2023학년도. 후기 학위수여식', date: '2024. 08. 22.', image: '../img/high_01_01.jpg' },
      { title: '2024학년도. 전기 학위수여식', date: '2025. 02. 20.', image: '../img/high_01_01.jpg' }
    ]
  },
  spirit: {
    pageTitle: 'SPIRIT OF KNUT',
    headingHtml: '<b>우리들의 반짝이는 청춘</b>의 순간을 기록하다.',
    items: [
      { title: '태국 해외봉사단', date: '2010.', image: '../img/high_01_01.jpg' },
      { title: '네팔 해외봉사단', date: '2011.', image: '../img/high_01_01.jpg' },
      { title: '케냐 해외봉사', date: '2011.', image: '../img/high_01_01.jpg' },
      { title: '필리핀 해외봉사단', date: '2013.', image: '../img/high_01_01.jpg' },
      { title: '몽골 해외봉사단', date: '2015.', image: '../img/high_01_01.jpg' },
      { title: '캄보디아 해외봉사단', date: '2016.', image: '../img/high_01_01.jpg' },
      { title: '라오스 해외봉사단', date: '2017.', image: '../img/high_01_01.jpg' },
      { title: '봉사활동', date: '1975.', image: '../img/high_01_01.jpg' },
      { title: '사회공헌단 농촌 봉사활동', date: '2019. 07. 13.', image: '../img/high_01_01.jpg' },
      { title: '벽화 동아리 그리담 봉사활동', date: '2017. 06. 30.', image: '../img/high_01_01.jpg' },
      { title: '봉사동아리 LEO', date: '2022. 05. 28.', image: '../img/high_01_01.jpg' },
      { title: '사랑의 연탄 나눔 봉사활동', date: '2022. 11. 12.', image: '../img/high_01_01.jpg' },
      { title: '국토대장정 출정식', date: '2009. 07. 05.', image: '../img/high_01_01.jpg' },
      { title: '교통대장정', date: '2013.', image: '../img/high_01_01.jpg' },
      { title: '국토대장정', date: '2007.', image: '../img/high_01_01.jpg' }
    ]
  }
}
